# Generated by Django 5.1 on 2024-09-25 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_remove_users_id_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.users')),
            ],
        ),
    ]
