# Generated by Django 5.1 on 2024-09-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farms',
            name='cropName',
            field=models.CharField(default='crop', max_length=50),
        ),
    ]
