# Generated by Django 5.1 on 2024-11-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0002_farms_cropname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farms',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='longitude',
        ),
        migrations.AddField(
            model_name='farms',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farms',
            name='soilType',
            field=models.CharField(default='crop', max_length=50),
        ),
    ]
