# Generated by Django 5.1 on 2025-04-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farms',
            name='workerEmail',
            field=models.EmailField(default=None, max_length=200),
        ),
    ]
