# Generated by Django 5.1 on 2025-04-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0002_farms_workeremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farms',
            name='workerEmail',
            field=models.EmailField(max_length=200),
        ),
    ]
