# Generated by Django 5.1 on 2025-04-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0003_alter_farms_workeremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farms',
            name='workerEmail',
        ),
    ]
