name: app
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.2

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # Additional dependencies
  cupertino_icons: ^1.0.8
  icons_plus: ^4.0.0
  http: ^0.13.5  # HTTP package for making network requests
  http_interceptor: ^1.0.0  # Package for managing HTTP requests and cookies
  google_sign_in: ^6.0.0
  webview_flutter: ^4.0.0
  url_launcher: ^6.0.9
  logging: ^1.0.2
  fl_chart: ^0.69.0
  flutter_svg: ^2.0.09
  provider: ^6.1.2
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.10.0
  google_maps_flutter_web: ^0.5.10
  geocoding: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For Flutter-specific settings
flutter:
  uses-material-design: true

  # Assets section for images and fonts
  assets:
    - assets/images/bg.jpg
    - assets/icons/

  fonts:
    - family: playfair
      fonts:
        - asset: fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
        - asset: fonts/PlayfairDisplay-VariableFont_wght.ttf
