# Generated by Django 5.1 on 2025-02-13 13:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0008_remove_users_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tickets",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("issue", models.TextField(default="")),
                ("issueDate", models.DateField(default=django.utils.timezone.now)),
                ("status", models.TextField(default="")),
                (
                    "email",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.users",
                    ),
                ),
            ],
        ),
    ]
