# Generated by Django 5.1 on 2025-02-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketPortal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickets",
            name="category",
            field=models.TextField(default=""),
        ),
    ]
