# Generated by Django 5.1 on 2025-04-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0002_tickets_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='status',
        ),
        migrations.AddField(
            model_name='tickets',
            name='resolvedData',
            field=models.DateField(default=None),
        ),
    ]
