# Generated by Django 5.1 on 2025-04-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0003_remove_tickets_status_tickets_resolveddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='resolvedData',
            new_name='resolvedDate',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='email',
        ),
    ]
