# Generated by Django 5.1 on 2025-04-25 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0004_rename_resolveddata_tickets_resolveddate_and_more'),
        ('home', '0012_alter_users_manageremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.users'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
