# Generated by Django 5.1 on 2025-04-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0005_tickets_email_tickets_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='status',
        ),
    ]
