# Generated by Django 5.1 on 2025-04-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0006_remove_tickets_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
