# Generated by Django 5.1 on 2025-04-25 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0007_tickets_status'),
        ('home', '0012_alter_users_manageremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='home.users'),
        ),
    ]
