# Generated by Django 5.1 on 2025-04-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0008_alter_tickets_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='email',
            new_name='email_id',
        ),
    ]
