# Generated by Django 5.1 on 2025-04-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0009_rename_email_tickets_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='resolvedDate',
        ),
    ]
