# Generated by Django 5.1 on 2025-04-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0010_remove_tickets_resolveddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='resolvedDate',
            field=models.DateField(default=None),
        ),
    ]
