# Generated by Django 5.1 on 2025-04-25 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0011_tickets_resolveddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='resolvedDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
