# Generated by Django 5.1 on 2025-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0012_alter_tickets_resolveddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='resolvedDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
