# Generated by Django 5.1 on 2025-04-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0013_alter_tickets_resolveddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='resolvedDate',
        ),
        migrations.AddField(
            model_name='tickets',
            name='closingDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
