# Generated by Django 5.1 on 2025-04-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0014_remove_tickets_resolveddate_tickets_closingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.TextField(default='Pending'),
        ),
    ]
