# Generated by Django 5.1 on 2025-04-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0015_alter_tickets_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='email_id',
            new_name='email',
        ),
    ]
