# Generated by Django 5.1 on 2025-04-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0017_alter_tickets_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.TextField(default='Pending'),
        ),
    ]
