# Generated by Django 5.1 on 2025-04-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0018_alter_tickets_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='closingMessage',
            field=models.TextField(default=''),
        ),
    ]
