# Generated by Django 5.1 on 2025-04-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0019_tickets_closingmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ticket_images/'),
        ),
    ]
