# Generated by Django 5.1 on 2025-04-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketPortal', '0020_tickets_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='image_data',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
