# Generated by Django 5.1 on 2024-09-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_users_email_alter_users_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phoneNumber',
            field=models.BigIntegerField(unique=True),
        ),
    ]
