# Generated by Django 5.1 on 2024-09-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_users_id_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='default_user', max_length=50, unique=True),
        ),
    ]
