# Generated by Django 5.1 on 2024-10-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
