# Generated by Django 5.1 on 2024-10-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_users_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
    ]
