# Generated by Django 5.1 on 2025-02-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_users_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isManager',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
