# Generated by Django 5.1 on 2025-04-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_users_ismanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='isManager',
            field=models.IntegerField(default=1),
        ),
    ]
