# Generated by Django 5.1 on 2025-04-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_users_ismanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='managerEmail',
            field=models.EmailField(default=True, max_length=200, null=True),
        ),
    ]
