# Generated by Django 5.1 on 2025-04-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_users_manageremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='managerEmail',
            field=models.EmailField(default=None, max_length=200, null=True),
        ),
    ]
