# Generated by Django 5.1 on 2024-11-27 16:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_remove_users_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activityName', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('farmName', models.CharField(default='', max_length=50)),
                ('email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.users')),
            ],
        ),
    ]
