# Generated by Django 5.1 on 2025-01-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="gdd",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activity",
            name="humidity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activity",
            name="rain",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activity",
            name="wind",
            field=models.IntegerField(default=0),
        ),
    ]
