# Generated by Django 5.1 on 2025-04-26 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_gdd_activity_humidity_activity_rain_and_more'),
        ('home', '0012_alter_users_manageremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activityName', models.CharField(default='', max_length=50)),
                ('assignedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmName', models.CharField(default='', max_length=50)),
                ('completionDate', models.DateTimeField(default=None)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('gdd', models.IntegerField(default=0)),
                ('rain', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('wind', models.IntegerField(default=0)),
                ('email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.users')),
            ],
        ),
    ]
