# Generated by Django 5.1 on 2025-04-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completionDate',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
