# Generated by Django 5.1 on 2025-04-28 03:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_tasks_completiondate'),
        ('home', '0012_alter_users_manageremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activityName', models.CharField(default='', max_length=50)),
                ('assignedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmName', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.users')),
            ],
        ),
    ]
