# Generated by Django 5.1 on 2025-04-28 04:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestions',
            name='assignedDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
