# Generated by Django 5.1 on 2024-09-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farm', '0002_farms_cropname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activityName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('farmName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farm.farms')),
            ],
        ),
    ]
